### ISSUE TITLE
Fix TypeError - String Indices Must Be Integers During guest_login()

### ISSUE THREAD

**Issue by Dsaad-People-Doc** [peopledoc/django-ticketoffice#30]

**Comment by Dsaad-People-Doc** [comment]
--

**Comment by Natim** [comment]
Do you have a TL;DR of what happened and how you fixed it?

**Comment by toopy** [comment]
Between the 0.4 and 0.5 we introduce an 'incompatibility' error between the application code and the stored data in db for the registration 'tickets' that encounter the error here:

- https://github.com/peopledoc/django-ticketoffice/blob/master/django_ticketoffice/decorators.py#L41

It generates something like:

```bash
Traceback (most recent call last):
...
  File "....env/local/lib/python2.7/site-packages/django_ticketoffice/decorators.py", line 180, in login
    return guest_login(request, self.ticket)
  File "....env/local/lib/python2.7/site-packages/django_ticketoffice/decorators.py", line 41, in guest_login
    request.user.id = invitation_data['user']
TypeError: string indices must be integers
```

Example of previously stored format with the django-uuidfield lib when working with a PG uuid column:

```
'"{\\"data\\": \\"example\\"}"'
```

Example of the expected format when using uuid field from the django PG contribs:

```
'{"data": "example"}'
```

To fix this we should update the 'tickets' data format for the not yet expired ones with the following script:

```python

import json
from datetime import datetime
from django_ticketoffice.models import Ticket

now = datetime.utcnow()

for ticket in Ticket.objects.filter(expiry_datetime__gte=now):
    data = json.loads(ticket.data)
    if isinstance(data, basestring):
        print('(#{}) {} -> {}: {}'.format(ticket.id, ticket.creation_datetime, ticket.expiry_datetime, ticket.data))
        ticket.data = json.loads(data)
        ticket.save()
```
